# Generated by Django 5.2.8 on 2025-11-20 21:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('TECH', 'Fixar problemas técnicos'), ('DB', 'Problemas relacionados ao DB'), ('FEATURE', 'Nova solicitação para desenvolver'), ('REMOVE', 'Remover funcionalidade'), ('ACCESS', 'Problemas de acesso')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_team', models.CharField(blank=True, choices=[('DEV', 'Desenvolvedores'), ('DB', 'Gerenciamento de Banco de Dados'), ('CS', 'Service Customer'), ('MG', 'Gerenciamento Geral')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em andamento'), ('PENDING', 'Pendente'), ('RESOLVED', 'Resolvido'), ('CLOSED', 'Fechado')], default='OPEN', max_length=20)),
                ('priority', models.IntegerField(default=3)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=200)),
                ('from_status', models.CharField(blank=True, choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em andamento'), ('PENDING', 'Pendente'), ('RESOLVED', 'Resolvido'), ('CLOSED', 'Fechado')], max_length=20, null=True)),
                ('to_status', models.CharField(blank=True, choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em andamento'), ('PENDING', 'Pendente'), ('RESOLVED', 'Resolvido'), ('CLOSED', 'Fechado')], max_length=20, null=True)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
